### ISSUE TITLE
When will broccoli-sass be upgraded to use node-sass 2.0.0-beta?

### ISSUE THREAD

**Issue by agentVargas2012R** [joliss/broccoli-sass#44]
Hi There,

I'm currently using the ember-cli project which has a dependency for broccoli-sass using 0.3.3. 

Is there a way I can build it or will there be a versino published that uses node-sass 2.0.0-beta?

**Comment by aexmachina** [comment]
ember-cli-sass has a beta version that uses node-sass 2.0.0-beta.​ That's
what we're using.

**Comment by agentVargas2012R** [comment]
Awesome!! Would you mind indicating the dependency?

**Comment by aexmachina** [comment]
`npm install --save-dev ember-cli-sass@3.1.0-beta` should do it.
