### ISSUE TITLE
update dependencies to allow node-sass@2.0.0

### ISSUE THREAD

**Issue by bartocc** [joliss/broccoli-sass#47]

**Comment by Ghostavio** [comment]
+1 please, right now it's impossible to run ember because of this

**Comment by Bargs** [comment]
Also getting bit by this

**Comment by ForSpareParts** [comment]
+1. It's not *impossible* to use ember-cli with broccoli-sass right now, but it makes upgrading to the latest version of Node prohibitively difficult. It appears that https://github.com/joliss/broccoli-sass/pull/43 resolves this -- any updates on getting it merged?

**Comment by aexmachina** [comment]
See #43 for instructions on installing a version that is compatible.

**Comment by michaelBenin** [comment]
Is it possible to version off node-sass in the package.json?

**Comment by aexmachina** [comment]
@joliss is not able to get these changes merged and published at this point, so until that happens I'm maintaining a fork at [aexmachina/broccoli-sass](https://github.com/aexmachina/broccoli-sass). The upcoming v0.4.0 version can be installed using:

```
"dependencies": {
    "broccoli-sass": "aexmachina/broccoli-sass#v0.4.x",
```

This branch will be updated with any patches as well if necessary, but hopefully we can get this merged back into the npm package before that's necessary! This uses node-sass ^2.0.1 and includes #43 for source maps support.
