### ISSUE TITLE
install fails on ember-cli 0.2.0

### ISSUE THREAD

**Issue by lmcardle** [joliss/broccoli-sass#51]
Running on ember-cli 0.2.0, the install fails:
```
$ ember install:npm broccoli-sass
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/development/JSProjects/testComponents/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
version: 0.2.0
Could not find watchman, falling back to NodeWatcher for file system events
Installing packages for tooling via npm.Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-iojs-1.5/binding.node
Installing packages for tooling via npm..module.js:322
    throw err;
          ^
Error: Cannot find module '/Users/development/JSProjects/testComponents/node_modules/broccoli-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:865:3
Build failed
Installed packages for tooling via npm.
```

**Comment by lolmaus** [comment]
I have just tried it and it worked for me. Must have been a network hiccup.

**Comment by joliss** [comment]
Based on the "Can not download" message, I'd suspect a network issue as well. @lmcardle, can you try again? You may also want to run `rm -rf node_modules; npm cache clean; npm install` first.

**Comment by joliss** [comment]
Hm maybe this is an issue between node-sass and the specific node version. We're investigating,

**Comment by chrisbenson** [comment]
Not sure if this is relevant / related, and apologize if it's not, but just in case:

https://github.com/sass/node-sass/issues/718

**Comment by lmcardle** [comment]
You seem to be correct. I was using iojs 1.5.  I just tried installing broccoli-sass on iojs 1.2 and it looks like it worked without any errors.

**Comment by joliss** [comment]
I just pushed v0.6.0, which depends on node-sass 3.0.0-pre. Let me know if this solves it please!

**Comment by joliss** [comment]
I'm assuming this is fixed, so I'll go ahead and close it.

If there are more installation issues with current versions, feel free report them straight to the [node-sass repo](https://github.com/sass/node-sass) too - they'll know better what to do.
