### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by lolmaus** [joliss/broccoli-sass#52]
Hi.

I'm receiving this when trying to run my project:

> Error: `libsass` bindings not found. Try reinstalling `node-sass`?`

I've seen this [fixed](https://github.com/joliss/broccoli-sass/pull/45) but it still doesn't work for me.

I seem to be running latest versions that should include the fix:

    "broccoli-sass": "^0.4.0",
    "node-sass": "^3.0.0-pre",

The problem happens on Node 0.12.0 and io.js 1.5.1. Everything works fine on Node 0.10, but 0.10 is no longer supported by Ember CLI, which i depend on.

:ambulance:

**Comment by aexmachina** [comment]
You will need to re-install node-sass when switching node/iojs versions, because the binary needs to be recompiled.

**Comment by lolmaus** [comment]
@aexmachina, every time i switched node/iojs versions, i did:

```bash
rm -rf node_modules/
npm cache clean
npm install --verbose
```

**Comment by jongold** [comment]
Yeah this is still broken for me - tried just about every version of node & io; only thing that works is using node-sass@3.0.0-pre. Can't get 2.0.x running at all.

**Comment by joliss** [comment]
Possibly the same as https://github.com/joliss/broccoli-sass/issues/51.

**Comment by escobera** [comment]
Is there a way to force node-sass version without forking this project?

**Comment by joliss** [comment]
I just pushed v0.6.0, which depends on node-sass 3.0.0-pre. Let me know if this solves it please!

**Comment by lolmaus** [comment]
I've just tried this:

```
nvm use iojs
rm -rf node_modules
npm cache clean
npm install --save-dev broccoli-sass@0.6.0
npm install
```

I confirm that my app starts fine and i no longer see the "libsass bindings not found" error.

Thank you, @joliss, you rock!

**Comment by dinebennett** [comment]
Hi, 

I seem to be running into this problem as well with version 0.6.5.

In my package.json file I have:
````json
    "broccoli-sass": "~0.6.5",
    "node-sass": "3.0.0-beta.7",
````

I am running Node v0.10.25.

Any advice? It would be much appreciated.
