### ISSUE TITLE
Bootstrap sass official no longer builds

### ISSUE THREAD

**Issue by technomage** [joliss/broccoli-sass#56]
Changes in 0.6.3 cause bootstrap sass official to no longer build.  The error is in _form.scss

**Comment by joliss** [comment]
Can you report this on the Bootstrap Sass repo please? For your/their information, the version 0.6.3 that you're using wraps **libsass 3.2.0-beta.2 via node-sass 3.0.0-beta.4**.

**Comment by blimmer** [comment]
@technomage There's something very, very wrong with node-sass 3.0.0-beta.4. I ran into the same thing. It seems that extends are fully broken in that version. I [opened an issue](https://github.com/sass/node-sass/issues/823) with them and pegged the version of broccoli-sass to 0.6.2 for now, like this:

```json
"broccoli-sass": "0.6.2"
```

Removing the caret will peg the version.

**Comment by joliss** [comment]
@blimmer Re your comment at https://github.com/sass/node-sass/issues/823#issuecomment-87734716, I'm guessing whatever bug is not so bad as to make it completely unusable then? I generally prefer to just track the upstream on broccoli-sass's 0.6.x branch, if at all possible.
