### ISSUE TITLE
Getting an @extend error

### ISSUE THREAD

**Issue by krzkrzkrz** [joliss/broccoli-sass#59]
With the current version (0.6.3), I get:

    You may not @extend an outer selector from within @media.
    You may only @extend selectors within the same directive.
    From "@extend .input-sm" on line 48 of tmp/tree_merger-tmp_dest_dir-VAbune7B.tmp/app/styles/bootstrap/_input-groups.scss

I am using broccoli-sass in an ember-cli app (v0.2.2). Downgrading broccoli-sass to a previous version (0.6.2) doesn't render any issues:

    npm uninstall --save-dev broccoli-sass
    npm cache clean
    npm install --save-dev broccoli-sass@0.6.2

Might be related to https://github.com/sass/libsass/issues/943

**Comment by joliss** [comment]
Can you report this on the libsass repo please? There's little we can do from the plugin's end.
