### ISSUE TITLE
Problem using bootstrap-sass & ember-cli-sass

### ISSUE THREAD

**Issue by abhilashlr** [joliss/broccoli-sass#60]
ember-cli-sass which has a dependency to broccoli-sass[broccoli-sass-source-maps] throws error in _input-groups.scss and _navs.scss due to an @import error.

**Comment by bogdansoare** [comment]
Same here
![screenshot 2015-04-06 15 01 07](https://cloud.githubusercontent.com/assets/2750170/7004035/d4e3209c-dc6d-11e4-8c98-08fe4e7b13d1.png)

**Comment by aexmachina** [comment]
See [comment here](https://github.com/aexmachina/ember-cli-sass/issues/38#issuecomment-90307689)
