### ISSUE TITLE
Latest node-sass update has broken broccoli-sass

### ISSUE THREAD

**Issue by selvaa89** [joliss/broccoli-sass#64]
Looks like node-sass update has broken broccoli-sass. broccoli-sass installation gets stuck at node-sass installation process.

node-sass version is 3.1.1

**Comment by selvaa89** [comment]
https://github.com/sass/node-sass/issues/970

**Comment by joliss** [comment]
I assume this is fixed, now that we depend on node-sas ^3.3.3.
